stocks_transformation:
  target: dev
  outputs:
    dev:
      type: bigquery
      threads: 16
      database: dwhhbbi
      schema: stocks_dev
      method: service-account
      keyfile: D:/OneDrive/Data engineer/Projekty/Signiture_project/ingestion/credentials/dwhhbbi-21142b907feb.json
      location: US
      dataproc_batch: null
